### ISSUE TITLE
Patreon scraper not working with webrequest==0.0.74

### ISSUE THREAD

**Issue by GeneralUltra758** [fake-name/xA-Scraper#101]
Needs webrequest==0.0.78 to work using (chromium_headless=False) is not a valid argument on version 0.0.74 
https://github.com/fake-name/xA-Scraper/blob/b46a97f05a675b09cff537455aedebc753483d3e/xascraper/modules/patreon/patreonScrape.py#L54

error on 0.0.74:
`TypeError: object.__init__() takes exactly one argument (the instance to initialize)`
tested with webrequest latest (0.0.78) works fine

https://github.com/fake-name/xA-Scraper/commit/28750f2e5c31fe2f807571ca04a46ba32b9cf4d3#r42985878

**Comment by fake-name** [comment]
Whoops, sorry about that! Forgot to update the requirements!
