### ISSUE TITLE
syntax error in rewrite/modules/rpc_base.py

### ISSUE THREAD

**Issue by mmsterful** [fake-name/xA-Scraper#12]
When trying to run anything in the manage module (haven't tried anything else yet), I get this, on a fresh installation with the dependencies installed via run.sh. Python version is 3.4.3.

````
(venv) user@host:/mnt/h/xA-Scraper$ python3 -m manage fetch fa
/usr/lib/python3.4/importlib/_bootstrap.py:1161: ExtDeprecationWarning: Importing flask.ext.markdown is deprecated, use flask_markdown instead.
  spec.loader.load_module(spec.name)
/mnt/h/xA-Scraper/venv/lib/python3.4/site-packages/flask/exthook.py:106: ExtDeprecationWarning: Detected extension named flaskext.markdown, please rename it to flask_markdown. The old form is deprecated.
  .format(x=modname), ExtDeprecationWarning
Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/mnt/h/xA-Scraper/manage/__main__.py", line 10, in <module>
    from .scrape_manage import do_fetch_all
  File "/mnt/h/xA-Scraper/manage/scrape_manage.py", line 21, in <module>
    from main import JOBS
  File "/mnt/h/xA-Scraper/main.py", line 26, in <module>
    import rewrite.modules.yiff_party.yiff_scrape as yps
  File "/mnt/h/xA-Scraper/rewrite/modules/yiff_party/yiff_scrape.py", line 23, in <module>
    import rewrite.modules.rpc_base
  File "/mnt/h/xA-Scraper/rewrite/modules/rpc_base.py", line 160
    call_kwargs = {'code_struct' : serialized, **call_kwargs}
                                                ^
SyntaxError: invalid syntax
````

Not sure what exactly is invalid about that syntax...

**Comment by fake-name** [comment]
Ok, that is strange.

I *think* this is a side-effect of some of the [changes in 3.5](https://docs.python.org/3/whatsnew/3.5.html#pep-448-additional-unpacking-generalizations). I guess that means it's currently >= 3.5. 

Let me remove the unpacking.

**Comment by fake-name** [comment]
I think that should fix it.

You will likely need to `python3 db_migrate.py db upgrade` after pulling.

I've switched to using [`alembic`](http://alembic.zzzcomputing.com/en/latest/) for db versioning (because rolling my own was just dumb) so everything is moving around, unfortunately.

**Comment by mmsterful** [comment]
whoops i just started the upgrade to 16.04 so I could get a newer version of python :V

thanks!
