### ISSUE TITLE
Patreon login returning HTTP error 429

### ISSUE THREAD

**Issue by moliorrs** [fake-name/xA-Scraper#156]
https://gyazo.com/06eb750d5db2c5b1f2b8b4ff1b217df7

I did see that you're closing patreon auth 401 issues, but I can't see what the fix is in the linked thread you post after that. https://github.com/fake-name/xA-Scraper/issues/20

I see you patched it in a push a while ago, but I think it might be borked again.

**Comment by fake-name** [comment]
It looks like some sort of patreon-side rate limiting.

Can you log in normally from the same address?

Patreon recently added their "device verification" bullshit, but that should have been fixed by https://github.com/fake-name/xA-Scraper/commit/a771de5437162d537278a33173878ce2b2ab034f (which I had forgotten to push).

**Comment by moliorrs** [comment]
Yes I can log in normal. I did hear about that as well.

**Comment by moliorrs** [comment]
also sorry for the bad title.

**Comment by fake-name** [comment]
No problem. Also, HTTP error 429 is very different from error 401, so I think that issue isn't relevant at all.

**Comment by moliorrs** [comment]
Alright fair enough on that bit.

**Comment by fake-name** [comment]
> Also, are the initial login checks (the requests for api.patreon.com/current_user) also throwing the 429?

If you're getting something like 401 \<retry\> 429 Fail, attempt login 429 \<retry\> 429, it might be just some new rate limiting. 

OTOH, if the *first* request throws a 429, I have no idea what to even do.

**Comment by fake-name** [comment]
Whoo, their rate limiting got *aggressive*. 

Hangon.

**Comment by moliorrs** [comment]
Sure thing!

**Comment by fake-name** [comment]
See if that resolves it.

I should drop the retry crap entirely. It was written a long time ago, was dumb then, and is more dumb now.

**Comment by moliorrs** [comment]
![21568c6e140900e04bb0b19105bc933c](https://user-images.githubusercontent.com/31002931/42434800-6ce5fef6-8322-11e8-9637-2b5c115f99a6.png)
Well, I tried your new edit.

**Comment by fake-name** [comment]
Well what the heck. The exact same code works fine for me.

**Comment by moliorrs** [comment]
I'm not sure what I am doing wrong, I've followed the readme to the letter.

**Comment by fake-name** [comment]
It's not you, it's patreon.

Basically, they have their rate-limiting detection for your IP (or some other thing) set much more sensitive then they do for my address, so things that work for me don't work for you.

**Comment by moliorrs** [comment]
I've even tried it through NordVPN, same result.

**Comment by moliorrs** [comment]
It hasn't worked.

**Comment by fake-name** [comment]
Actually, dumb question. Can you check your e-mail? Patreon added this dumb new device verification thing, and I wonder if this is a side effect of it somehow. They should have sent mail about confirming a new device if so.

**Comment by moliorrs** [comment]
*cough* Yeah I see like 30+ verify this device emails now...

**Comment by moliorrs** [comment]
Ok now there is only a 401, so thats something at least
![7dbe50603b30b80c593c57355dd423e4](https://user-images.githubusercontent.com/31002931/42437660-bd1ef978-832b-11e8-8e8c-f4db903915cf.png)

**Comment by fake-name** [comment]
I wonder if they block or limit your address after N log in attempts.

Can you clear your cookies in a browser, and try logging in?

**Comment by moliorrs** [comment]
I'm going to wait a full day and then give it another shot. I am able to log in through the website, on multiple browsers at once. Hopefully once I wait, it'll let em verify it.

**Comment by fake-name** [comment]
Yeah, sorry about all this.

The device verification stuff was kind of a mess, and I forgot to push the fixes initially too! Doh

**Comment by moliorrs** [comment]
Well there seems to be some new stuff, looks like it connected but you tell me 
![303a90180af9147bb263ef1d4e7b2607](https://user-images.githubusercontent.com/31002931/42491091-654bbaae-83e1-11e8-99f1-211a0a8870cb.png)

**Comment by fake-name** [comment]
The save path you've configured is not writable.

Check you can actually create files where you've configured the scraper to save things.

**Comment by moliorrs** [comment]
Well hot damn, there we go! It now works :)

**Comment by fake-name** [comment]
wewt!

**Comment by moliorrs** [comment]
Thanks for fixing this, I appreciate it. Saves me ages of manually scraping it.

**Comment by fake-name** [comment]
No problem.
