### ISSUE TITLE
request: adding support for non-file based literature scraping, DA specifically

### ISSUE THREAD

**Issue by rawesomeawesome** [fake-name/xA-Scraper#163]
many deviants and fa users post lots of literature, which is a pain to download manually, and no scrapers provide support for downloading them either. it'd be amazing to see an addition for this kind of scraping

**Comment by fake-name** [comment]
It already scrapes the content text-body of both fa and da.

Do you mean something else?

**Comment by rawesomeawesome** [comment]
it does? i've found that literature is usually separated from the description and so scrapers dont pick it up... and the folders for my artists who post literature mainly are empty aside from the few pics they've posted between stories

**Comment by rawesomeawesome** [comment]
looking at the rapidly scrolling log of manage fetch, it looks as if it tries to download something from the link, but nothing appears in the download folder or in the gui

**Comment by rawesomeawesome** [comment]
it is scraping pdf's and txt files it seems, but works of literature without a download option appear to be ignored

**Comment by rawesomeawesome** [comment]
im not well versed in python, but i assume it would only require something similar to the scraping of descriptions modified to catch the text body of the literature

**Comment by rawesomeawesome** [comment]
as an unrelated issue, i'm having trouble accessing my scraped database gui from outside my computer, i tried my local network ip address with and without the :6543

**Comment by fake-name** [comment]
It should be pretty straightforward. Do you have an example page I can check with?

**Comment by fake-name** [comment]
?

**Comment by fake-name** [comment]
You can also email at <anything> @ fake-url [dot] com (it's a catchall address), if you don't want stuff posted publicly.
