### ISSUE TITLE
Patreon content

### ISSUE THREAD

**Issue by RobertShippey** [fake-name/xA-Scraper#167]
Hi, 

I guess they've changed the way they return info or something becuase this doesn't look right, or am I doing something wrong. 

I'm running on a clean install from today (new Scraper here, hi hi)

<img width="803" alt="screen shot 2018-08-01 at 19 59 50" src="https://user-images.githubusercontent.com/787949/43542755-d504cd4a-95c5-11e8-8b76-58ff84c5d04f.png">

It means all the links to content seem broken too. e.g `/source/by-site/[%22post%22,%20%2219548336%22]`

Let me know where to look to send you log files if needed. 

Thanks.

**Comment by fake-name** [comment]
Yeah, looks like they restructured how the content is packaged in their json.

Will have a look, probably this weekend.

**Comment by RobertShippey** [comment]
Wonderful. Great tool btw :)

**Comment by fake-name** [comment]
OK, I think there's actually no issue.

I never implemented deep-links into the patreon site, but the actual relevant content should still be being fetched properly. You should see image content on item mouse-over for images, and the download content directories should be fully populated for the fetched content.

**Comment by fake-name** [comment]
For the most part, the web-interface is mostly to check that the scraper is seeing posts at all, and to get a quick overview of image content. Implementing a comprehensive content viewier is a lot of work, and your platform's file-browser does a better job anyways.
