### ISSUE TITLE
FA Scraping errors... did I lose any data?

### ISSUE THREAD

**Issue by Aidolii** [fake-name/xA-Scraper#174]
Log can be found here, two week expiration:

https://pastebin.com/XeJiS2Kn

The weird directory format has to do with my 'portable' setup for my Windows PC, but I worked out the problems with that ages ago, I've scraped tons of FA and DA galleries already.

Today though I ran into these errors and I'm concerned there's a loss of data. Could you interpret these errors and let me know if there's any long term problems with the database resulting from this? Using SQLite or whatever it's called.

**Comment by fake-name** [comment]
Nah, it's just a post where the image has gone missing (FA has a fair number of these). It's no problem.

I don't think there's anything you can reasonably do that would fuck up the database. SQLite is extremely robust. About the only thing you could to that would cause irrevocable damage would be to actually delete the database file.

**Comment by Aidolii** [comment]
My internet might be hiccuping. Does xA-Scraper ever retry a failed submission later?

**Comment by fake-name** [comment]
It should retry on the next run.
