### ISSUE TITLE
Patreon scraping fails-requires email verification

### ISSUE THREAD

**Issue by warriorbard** [fake-name/xA-Scraper#177]
When trying to scrape patreon, the log in fails and I end up getting an email like this, asking me to click a link to verify. Even if I click the link, it still fails on the next run and sends another email.

Hi ...,

Someone has requested to verify a device for your Patreon account.

Details:

Country: ..
IP: ...
Time: Sunday, August 5 at 4:00pm, Pacific Time
If this was you, click the button below.

**Comment by fake-name** [comment]
I think patreon only lets you have one outstanding verification result.

Basically, delete `cookies.lwp`, `cookiestmp.lwp` from the program directory, run the scraper *once*, accept the e-mail, and try again.

**Comment by fake-name** [comment]
Any luck?

**Comment by warriorbard** [comment]
That seemed to do it. Thanks!

**Comment by fake-name** [comment]
cool!
