### ISSUE TITLE
DeviantArt Scraper failing to login

### ISSUE THREAD

**Issue by Aidolii** [fake-name/xA-Scraper#183]
I think it might have something to do with the recaptcha DeviantArtis now using.

I put in my 2captcha API key into the settings (I tested it on my chrome extension, works), but it didn't help.

**Comment by fake-name** [comment]
The only thing that currently uses 2captcha is fa.

If da is using recaptcha, I may finally have to implement generic captcha support in https://github.com/fake-name/WebRequest

**Comment by Aidolii** [comment]
Well, it is. I verified my login details in the settings were correct, and on the website I logged out and when it wanted me to log back in I had to solve a recaptcha.

**Comment by fake-name** [comment]
Fucking DA. "We have users, quick make the site so shitty people are forced to pay for a membershit".

**Comment by Aidolii** [comment]
You could do a manual login thing like you did for FA

**Comment by fake-name** [comment]
Recaptcha makes it a giant pita.

**Comment by Aidolii** [comment]
I see. Well users that don't have 2captcha like us probably wouldn't like having to register for it to continue using the program. The process of getting funds onto 2captcha is quite a pain in and of itself.

**Comment by Aidolii** [comment]
It sounds like whatever you have planned will take a while. Is there any way to transplant a login cookie in the meantime?

**Comment by fake-name** [comment]
Probably? The lwp cookiejar format is supposed to be somewhat portable (though in this case "portable" means it can open the file from the perl library that invented the format).

I haven't poked around with it much, but it's just ascii. Maybe that + looking at the login cookies in your browser could lead somewhere.

**Comment by Aidolii** [comment]
`looking at the login cookies in your browser could lead somewhere.`

oh boy I can't wait to figure out how to make that work on Windows

I was hoping to just extract the cookie data with chrome/firefox the same way you do with PixivUtil2

```
      1. Open Firefox/Chrome.
      2. Login to your pixiv.
      3. Right click the page and select View Page Info -> Security tab (Firefox), or
         Right click on the leftmost address bar/the (i) icon (Chrome)
      5. Click the View Cookies button.
      6. Look for Cookie named = PHPSESSID.
      7. Copy the content value.
      8. Open config.ini, go to [Authentication] section, paste the value to
         cookie.
```

**Comment by Aidolii** [comment]
fuck

**Comment by Aidolii** [comment]
I have UPnP, yes. That would work fine.

As an aside, have you looked into this?

https://chrome.google.com/webstore/detail/recaptcha-solver/hapgiopokcmcnjmakciaeaocceodcjdn

It's what I use on my browser with 2captcha, it might give you some sort of hints as how to implement it? I dunno.

**Comment by fake-name** [comment]
It's not I don't know how to deal with it, it's just that it's a lot of work.

Basically, to do things properly, I have to poke a hole through the local NAT (if any), and spin up a (probably SOCKS5) proxy on it for the captcha solving service to use to bounce their requests off the local address. At that point, it's pretty straightforward.

**Comment by fake-name** [comment]
FWIW, the implementation is going here, and I've started on it.

https://github.com/fake-name/WebRequest/tree/7cf58dc7da042341fc6359cf587341a253d5922c/WebRequest/Captcha

**Comment by fake-name** [comment]
Hmmm, DeviantArt isn't popping a ReCaptcha on me. I think they might suspect shit from your IP.

**Comment by Aidolii** [comment]
Well, I could give you access to a proxy I use. I'm not trying to use xA-Scraper from behind it, but proxies pretty much always trigger recaptchas.

**Comment by fake-name** [comment]
I can more or less figure out what it'd look like. Or just try getting to the login page through TOR (which I just thought of).

**Comment by Aidolii** [comment]
I'm not currently using a proxy, I was just offering you access to one. I only use proxies on some websites.

I think my IP is just flagged as suspicious for whatever reason.

**Comment by fake-name** [comment]
Oh, derp.

**Comment by fake-name** [comment]
Ironically, I can't seem to even persuade DA to captcha me even after trying random passwords for the user "admin" for about 10 minutes.

Can you stick the source of the login page with a captcha on pastebin or somewhere I can see it?

**Comment by Aidolii** [comment]
Here you go. Post your email if you'd like access to a proxy I know will trigger the ReCaptcha

https://pastebin.com/ijgFvX5c

The ReCaptcha doesn't trigger until I press the button to log in, not sure if that is significant.

**Comment by fake-name** [comment]
That's not my bot. I use https://pyup.io/, which is a service to automatically update dependencies in requirements.txt.

> The ReCaptcha doesn't trigger until I press the button to log in, not sure if that is significant.

Oooh, yeah, I might actually need the proxy, then. \<anything\> @ fake-url \[dot\] com should get to me. With anything being a wildcard forward.

**Comment by Aidolii** [comment]
I emailed you a couple days ago with the proxy, I assume you've just been busy?

**Comment by fake-name** [comment]
Yeah, sorry, I generally don't have too much time for this sort of thing during the week.

**Comment by fake-name** [comment]
Even logging in via that proxy, I just log in, without a captcha.

I'm using firefox + the VPNetworksLLC Proxy plugin, with my location set to "central usa".

I created a garbage user acct to test with:

DA:
User: <sent via e-mail>
Pass: <sent via e-mail>

I wonder if DA does stuff on a per-account basis. Can you just switch accounts?

Note that there *is* a captcha on https://www.deviantart.com/users/rockedout, but there doesn't seem to be a captcha on https://www.deviantart.com/users/login. What URL are you using for confirming with?

**Comment by fake-name** [comment]
Ok, give that a shot. The scraper not tries a fair bit harder to be less dumb, and it'll also dump the login page source to a file if/when it does hit a captcha.

**Comment by Aidolii** [comment]
Thus far everything seems to be working well!

**Comment by fake-name** [comment]
Kewl! Closing then.
