### ISSUE TITLE
move login code to settings.py

### ISSUE THREAD

**Issue by CuddleBear92** [fake-name/xA-Scraper#19]
having a hard time getting the first setup up and going.
getting a syntax error with the run.py with the line ```if [ -d "venv" ]```

running the main.py doesnt seem to make a database and im not sure how to fix this one.

Tried following the written stuff on here  from the issues and main readme. maybe im missing something.
installed all the requirements in the requirements text file with pip. 

dont have a database. unsure about the postgres settings in the settings.py aswell.

if its an user error from my part i think the wiki needs to be filled out to atleast get users up and running.

**Comment by fake-name** [comment]
`run.sh` is a shell script, it's expected you execute it from bash, not python (`./run.sh`).

If you're not on linux, You're going to need to figure out the equivalent commands for `cmd.exe`.

Postgres setup (well, DBA stuff) is a complete field in-and-of-itself, and kind of outside of the scope of any client-project specific readme. Postgres has a decent [getting started](https://www.postgresql.org/docs/9.6/static/tutorial-start.html).

**Comment by CuddleBear92** [comment]
got it running with bash for ubuntu for windows i believe.
had some issues with grabbing the timezone automatically and struggled a bit with what line to edit in the util file. 

now im stuck at the login screen. 
i filled out the postgres username, password, database name and address in the settings.py and guessed that would be the info used for the login. it didnt work.
the database is in place in the postgres admin 4 window and the run.sh seems to get this correctly without serious errors and starts hosting the login on localhost.

do get some warnings about flask though, attached screenshot just in case.

![cuddlebear pcare_mntdprogramsscraper_2017-10-15_02-24-49](https://user-images.githubusercontent.com/8496821/31580446-3bd28964-b150-11e7-996d-d19654af5421.png)

**Comment by fake-name** [comment]
Yeah, the depreciation warnings are due to flask packages using other, outdated flask packages. Yes, it's annoying, I haven't been able to fix it, though. 

Cool that it's working! Nice!

I'll answer the password stuff in your other bug report.

**Comment by CuddleBear92** [comment]
well you state that you have given me the info, i guess you mean pointing to setting up and logging in on the database, which your program does just fine. the issue is that i cant login on the hosted site you host. 
it seems im missing something. looked over all the text here on the github and i still dont get it.

the only info i seem to find about that login is that it used to be hardcoded in wsgi_server.py
which is no longer in the files it seems.

would really love to get this working so i can recommend without issues to the many others that might be interested.

**Comment by fake-name** [comment]
Oh derp, I somehow missed that I got two reports from two people with the same issue at the same time. Sorry about that.

The username/password is currently hard-coded [here](https://github.com/fake-name/xA-Scraper/blob/master/rewrite/__init__.py#L26).

**Comment by fake-name** [comment]
I should really move the password stuff into either `settings.py`, or the database proper.

**Comment by CuddleBear92** [comment]
thank you for that info. i can login and actually use the program now! :O 
really need some basic write up on how to get it running. bash for windows worked great though.

**Comment by fake-name** [comment]
A lot of this is because I recently rewrote large chunks of the management internals, including completely replacing the entire database interface layer and the web UI routing/templating language.

This basically invalidated most of the documentation I've written so far, and I've not had time to update it.

**Comment by fake-name** [comment]
That should cover it, I think.
