### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by StromiBergWitz1** [fake-name/xA-Scraper#190]
I need help I don't know how to setup this.

**Comment by fake-name** [comment]
Step 1: Get you a debian based linux install (ubuntu 16.04 is is my development OS of choice)  
Step 2: Get you a python 3.5 install (probably present by default).  
Step 3: Manually install `pip` into the python3 install.   
Step 4: Copy `settings.base.py` to `settings.py`, edit for your accounts/paths/etc.  
Step 5: `./run.sh`, which should bootstrap the needed dependencies into a venv.

**Comment by StromiBergWitz1** [comment]
But how does it work on Windows?

**Comment by fake-name** [comment]
Uh, it doesn't?

If you're on windows 10, apparently another user has had some success running it under the [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/install-win10). See [here](https://github.com/fake-name/xA-Scraper/wiki/Install-and-usage-on-Windows-10).

**Comment by StromiBergWitz1** [comment]
Is it Ubuntu or Ubuntu 18.04 on the store both exist and I don't know what is mentioned here.

**Comment by fake-name** [comment]
Dunno, I don't use windows 10.
