### ISSUE TITLE
TypeError when scraping Patreon

### ISSUE THREAD

**Issue by AnotherRick** [fake-name/xA-Scraper#194]
I was trying this out on both a fresh Virtualbox Ubuntu 16.04 server and a DigitalOcean Ubuntu 16.04 server. Both the same error.

```
Main.PatreonGet.Thread-2 - ERROR - Exception when retreiving artist <artist name>
Main.PatreonGet.Thread-2 - ERROR - Traceback (most recent call last):
  File "/<username>/xA-Scraper/rewrite/modules/patreon/patreonScrape.py", line 403, in getArtist
    json.dump(newArt, fp)
  File "/usr/lib/python3.5/json/__init__.py", line 179, in dump
    fp.write(chunk)
TypeError: a bytes-like object is required, not 'str'
```

Checking Patreon (PAT) errors on the web interface shows a file not found error.

**Comment by MukiEX** [comment]
It's not just me! Is scrape working in an earlier commit?

**Comment by fake-name** [comment]
Sorry it's taken me so long to get back to this.

Ok, wow, that was spectacularly dumb. Apparently in 088b45734735ec8a701c6da42501ad90ec50f502 I was doing \~\~something\~\~, and added some changes for testing that I then forgot to remove. I have no fucking idea what I was thinking, but it seems to be working now.
