### ISSUE TITLE
How do I log in to my server?

### ISSUE THREAD

**Issue by jtara1** [fake-name/xA-Scraper#2]
OS: Ubuntu 16.04

I got all the modules & dependencies installed by running run.sh.

I copied settings.base.py to settings.py & updated values.

I created a postgres database by running 

    sudo su postgres

    createdb myapp

Then I run

    python3 serverTest.py

I go to link given in the terminal & get redirected to login page, but can't figure out my own user and password for this.

Here's part of my settings.py

	"postgres" :
	{
		"username" : "postgres",
		"password" : "mypass",
		"address"  : "localhost",
		"database" : "myapp",
	},
       "dbConf":
	{
		"namesDb"         : "olabukoo",
		"retrevialTimeDB" : "retreival_times",
		"erroredPagesDb"  : "errored_pages",
		"successPagesDb"  : "retrieved_pages",

		"uploadedImages"  : "upload_images",
		"uploadGalleries" : "upload_galleries"

	}

**Comment by fake-name** [comment]
Username and password are currently hardcoded in [wsgi_server.py](https://github.com/fake-name/xA-Scraper/blob/master/wsgi_server.py#L21), mostly because I'm lazy, and the protection is just intended to keep idle explorers out.

The login redirection can be cranky sometimes too, you may have to manually navigate to the root after login (for some reason, the conditional login sometimes doesn't properly redirect to root, and it hasn't bothered me enough to actually fix).

**Comment by fake-name** [comment]
Whoops, closed by accident.

**Comment by fake-name** [comment]
I guess I should also comment that this is one of my oldest projects (it's the second project I wrote when I started learning python), so some of the code quality internally is HORRIBLE. 

It works just enough that I haven't had the motivation (or time) for a rewrite, but it's right on the edge.

**Comment by jtara1** [comment]
Ok thanks. This project looks really interesting. This is beyond anything I've done so it's impressive old or not.

Does it run like cron or anacron? 

i.e., if the program isn't running in my terminal will it still download images from the sites next time I start the program and enough time has passed?

I came to this repository looking for projects I could borrow from to easily download from pixiv, tumblr, & deviant art in particular, and I may try to see what I can make of some of the plugins.scrapers classes for each of the sites.

**Comment by fake-name** [comment]
No, it has it's own internal scheduler, and the application has to be active in a terminal session to work. I leave it running in screen.

`run-all.py` in the repo root should manually execute most (?) of the plugins without waiting on the scheduler, and adding the few I haven't patched in shouldn't take much effort (they all have the same interface).

**Comment by jtara1** [comment]
Thanks for all the help.

**Comment by fake-name** [comment]
Let me know if you run into other issues. Every few months I check to make sure the various site scrapers haven't gone stale, with the targeted sites changing their structures enough to break things, and I haven't done that too recently. It's possible some of the sites have updated it out of functionality.

Fortunately, I'm pretty good at [writing](https://github.com/fake-name/AutoTriever) [web](https://github.com/fake-name/MangaCMS) [scrapers](https://github.com/fake-name/ReadableWebProxy) at this point, so I should be able to fix that sort of thing in an evening or so.

**Comment by jtara1** [comment]
Will do. Half of my repositories are intended for scraping so I'm really interested in learning from your work, already followed you.
