### ISSUE TITLE
Settings module not found?

### ISSUE THREAD

**Issue by supermrdoctorwho** [fake-name/xA-Scraper#204]
I'm not sure if this affects anyone else, but in "xA-Scraper-master/rewrite/__init__.py". it seems to be having an issue when trying to install for me, in that on line 8, it cannot find the settings module. I cannot figure out why. I suspect it just can't find which one it is, if anyone has a fix that would be great
Screenshot in command line attached.
![screenshot from 2018-10-12 21-18-11](https://user-images.githubusercontent.com/44101426/46892202-22258f00-ce5c-11e8-9c0b-387b03c5cc02.png)

**Comment by fake-name** [comment]
From the readme:

> If using postgre, DB setup is left to the user. xA-Scraper requires it's own database, 
and the ability to make IP-based connections to the hosting PG instance. The connection 
information, DB name, and client name must be set by copying settings.base.py to `settings.py`,
and updating the appropriate strings.

**Comment by fake-name** [comment]
Improved readme documentation:

> Configuration is done via a file named `settings.py` which must be placed in the
repository root. `settings.base.py` is an example config to work from. 
In general, you will probably want to copy `settings.base.py` to `settings.py`, and then 
add your various usernames/password/database-config.
