### ISSUE TITLE
Commit f70505f breaks the scrapper.

### ISSUE THREAD

**Issue by Daiyousei** [fake-name/xA-Scraper#283]
When starting the script, the folowing error is sent.
```
Launching executable.
Sqlite database path: 'sqlite:////home/xxx/xA-Scraper/sqlite_db.db'
Traceback (most recent call last):
  File "db_migrate.py", line 7, in <module>
    from xascraper import app, db
  File "/home/xxx/xA-Scraper/xascraper/__init__.py", line 74, in <module>
    from . import views
  File "/home/xxx/xA-Scraper/xascraper/views/__init__.py", line 2, in <module>
    from . import main_views
  File "/home/xxx/xA-Scraper/xascraper/views/main_views.py", line 28, in <module>
    import main
  File "/home/xxx/xA-Scraper/main.py", line 57, in <module>
    (tus.GetTumblr,  settings["ng" ]["runInterval"],  "ng"),
KeyError: 'ng'
```

The issue had been introduced with the commit f70505f 

Can be fixed by adding the folowing in settings.py, in the dictionary "settings"
```
	"ng" :  # newgrounds 
	{

        "dlDirName"       : "NewGrounds",
        "shortName"       : "ng",
        "runInterval"     : 60*60*6,   # every 6 hours
	},
```

In the future, please make sure to update the settings.base.py to reflect the required minimal config.

**Comment by fake-name** [comment]
Yeah, sorry, that's a WIP.

**Comment by Daiyousei** [comment]
Ahah, nous problem :)

That was purely coincidental, though. I had to reinstall it yesterday evening, a few hour after the commit :p
A few hours before I would not have noticed.

Also : yep, I'm running this thing, mainly for DA.
