### ISSUE TITLE
FurAffinity cookie retrieval broken

### ISSUE THREAD

**Issue by mmsterful** [fake-name/xA-Scraper#3]
When I try to use this tool's Furaffinity scraper, it tries to log in and fails.

It's not able to handle the newer FA login page, and instead of loading valid cookies from the LWP file, it blanks the file upon startup.

Commenting out checkCookie() in faScrape.py and references to it in scraperBase.py, then saving the cookie file with proper content after it's blanked seem to fix the initial problem, and allow it to fetch a gallery, but it doesn't get all the items in a gallery with content that only shows to logged-in users, showing that it's not actually successfully logging in with the cookies.

**Comment by fake-name** [comment]
Huh. Someone's actually using this thing! Awesome!

Thanks for the issue report. I'll have a poke at fixing the issue over this weekend. It shouldn't be too big a deal to figure out what they changed (I admit I haven't looked in a while).

**Comment by mmsterful** [comment]
It seems to be the only thing out there that's a scraper that runs itself! It's perfect for my needs, except that I'm going to have to add artists one at a time :p

**Comment by fake-name** [comment]
> I'm going to have to add artists one at a time :p

Can you clarify? It's pretty trivial to just shove a whole list of artists into the DB, either manually (SQL), or via a little script.

**Comment by fake-name** [comment]
Oooohh, new login system apparently has a capcha. That's a problem.

**Comment by fake-name** [comment]
Ok, workaround is in-place.

You have to use the web-interface to manually solve the login captcha (it's fetched from FA on-the-fly), but once you have a valid login cookie, it should be valid for the forseeable future.

**Comment by mmsterful** [comment]
excellent! :)

**Comment by mmsterful** [comment]
and in clarification, I was just looking at the web interface; my coding skills are less than rudimentary but I can probably figure out an SQL query to do what I need.

**Comment by fake-name** [comment]
I need bulk import for myself at this point, so I can sync some of the tumblr RSS feeds I follow into the scraper. I'll put something together this weekend, if you can wait.

**Comment by fake-name** [comment]
I threw together a bulk-import thing. There's a new script in the root of the repo: `scrape-manage.py`, which has a few command-line functions, including bulk-importing a list of names from a text file. Run without commands, it prints how to use it.

You will need to source the virtualenv before use: `source venv/bin/activate`. `run.sh` does this for running the application normally.

**Comment by mmsterful** [comment]
awesome! I really appreciate all the work you've put into this. :)

**Comment by fake-name** [comment]
NP. I really should get around to adding support for ArtStation at some point as well.
