### ISSUE TITLE
Ratelimiting FurAffinity downloads now required

### ISSUE THREAD

**Issue by mmsterful** [fake-name/xA-Scraper#31]
```
Your IP address has been banned.

Your IP address is: [address]
Reason: Scripted, non rate limited mass downloading of gallery and submission pages.
Contact [address] for details.

If you feel this is in error, please send an email to [address 2] with a copy of this message attached.
```

Welp. I'm going to email them and find out what they'd like me to limit it to. I didn't mention this project by name, if that's important.

The ban hit when xA-Scraper was in the middle of a `manage fetch fa` job, and I ended it rudely with a pair of Ctrl-Cs. I dunno if that'll affect the integrity of the local mirror or not.

**Comment by fake-name** [comment]
I'm pretty sure they've had rate-limiting for a long time, it's just hard to hit. I seem to remember having to reset my modem IP at one point years ago to get around it.

Anyways, the easy way to reduce the scrape-rate is just turn down the number of scraper threads. It'd been 2 for a while, and I upped it to 3 recently for some reason. Anyways, I reset it down to 1. It'll still fetch everything, it'll just take longer.

> The ban hit when xA-Scraper was in the middle of a manage fetch fa job, and I ended it rudely with a pair of Ctrl-Cs. I dunno if that'll affect the integrity of the local mirror or not.

There *shouldn't* be **anything** you can do to the local process that'll result in the database getting corrupted. Even the migrations should be transactional, so either they'll succeed or abort with no changes.

**Comment by mmsterful** [comment]
Good to hear on the database integrity front. I'll see what they say about the ratelimiting and/or unbanning me.

It specifically says "galleries and submission pages," so I assume they looked at their logs. I'll turn down the scraper threads; if they ask for a specific bandwidth limit, I'll see if there's anything I can do proxy/VPN-wise that'd do that.

An idea I had a while back: one might be able to save FA's bandwidth/CPU power and our scraping time by storing a "signature" of, say, the latest scraped page of an artist's gallery, including a list of submission IDs. Upon the next scrape, it could check for new items, and stop hitting gallery pages as soon as it hits a string of consecutive already-scraped submissions, assuming that it's already got the rest of the gallery.

One potential complication of this would be if FA users can change the effective submission date of a submission without creating a new one; I'm not sure whether or not that's the case. Another would be if xA-Scraper tracks whether a submission's been deleted since scraping or not.

**Comment by fake-name** [comment]
I turned down the thread-count, you should be able to just pull.

> An idea I had a while back: one might be able to save FA's bandwidth/CPU power and our scraping time by storing a "signature" of, say, the latest scraped page of an artist's gallery, including a list of submission IDs. Upon the next scrape, it could check for new items, and stop hitting gallery pages as soon as it hits a string of consecutive already-scraped submissions, assuming that it's already got the rest of the gallery.

I do store a list of submission pages, and don't touch submissions that have been fetched. However, I do walk the entire gallery list every time. That could probably be worked around as you describe. 

If more rate-limiting is needed, it'd be basically trivial to add, so  there's that.

**Comment by mmsterful** [comment]
> Hi.
> 
> Generally we are not against scraping if it is being done with consideration to our server resources and does not impact the performance of the live website.
> To that extent the best time to be doing this is off-peak hours, which ranges from 05:00 to 18:00 EDT, and only when the number of registered users online (bottom of the page) is below 10k.
> Rate limit of no more than 2-3 requests/sec. Higher than that and you risk getting caught by the semi-automated IP ban system again.
> It is preferable that you use a consistent, custom User Agent string with your requests so they are identifiable.
> 
> That said, the ban on your IP has been lifted. Don't get caught again :)

**Comment by fake-name** [comment]
Yeah, from what I've heard the few times they've had issues or people rage-quit and broke shit, I think the proper response is "what caching infrastructure". 

I think their internal systems are probably a shit-show.
