### ISSUE TITLE
Basic setup guide for Windows users on the wiki

### ISSUE THREAD

**Issue by CuddleBear92** [fake-name/xA-Scraper#34]
need to setup a basic windows guide for newer users aswell as reminders for myself at a later date.

(this is more of a note to myself) 

- [x] Cover Installing Bash/Linux Subsystems on Windows 10
- [x] Cover Installing Python 3.6
- [x] Cover Installing requirements
- [x] Cover editing your own settings file
- [x] Cover Installing Postgres
- [x] Silent/Quiet Start + Start on boot with a vbs script.

----------------
- [ ] Need Screenshots for the Bash install
- [ ] Need Screenshots for the Python Install
- [ ] Need Screenshots for the rest

**Comment by fake-name** [comment]
> Bonus? how to make it into a daemon or to run in the background?

In linux, I leave it running in a `screen` session, but I have no idea how that'd work on linux with a GUI (I think you can have background screen sessions on linux when a GUI is active, but I don't have any linux boxes with X installed on them).

For windows, I think you could use background task scheduler? It may still require a user being logged in.

**Comment by CuddleBear92** [comment]
sounds good, totally forgot about postgres install in it. will add that soon. i might want to upload a folder of screenshots for the wiki to make it a bit better though.

**Comment by fake-name** [comment]
It's worth noting that with the recent switch to using `sqlalchemy` for DB stuff, it'd *probably* be relatively straightforward to add support for `sqlite3` as a database backend. This would remove the need for postgresql entirely.

This project actually started with a sqlite3 backend, but it turns out that once your database grows beyond a certain point, the index warming time when `sqlite` has let the indexes drop out of cache lead to 30+ second render times for the first page-view after the server had been sitting for a while.

Really, the only postgres specific thing I'm using is the [`ENUM` and `JSON` types](https://github.com/fake-name/xA-Scraper/blob/master/rewrite/database_models.py#L22-L27). 

It looks like there's a more generic [`ENUM` type](https://groups.google.com/forum/#!topic/sqlalchemy/yxxWGRYLC64), and the JSON type could be manually serialized/unserialized. I'm not using any of the postgres-specific features that allow in-database querying into json datatypes.

**Comment by CuddleBear92** [comment]
well if you can make it a bit more easy to use for the common folk then im sure people would love it. 
i cant get it running without postgres at all and manually making a database in the pgadmin program.

something the script should do imo. 

also i have seen so many programs that is much more heavy than this that use sqlite like hydrus and shoko anime for example.

yes sqlite is slow but it really needs to be cached a bit to be effective.
i know that shoko had issues with sqlite before they added caching and now its as fast as all the other options that program had.


also a note, that might be an windows issue.
timezones fail to be recognized at all and needs to be edited manually. (atleast the error points to the right file to edit)

**Comment by fake-name** [comment]
> also i have seen so many programs that is much more heavy than this that use sqlite like hydrus and shoko anime for example.

It's not that it didn't work, it's that there are certain edge-cases where it's performance is annoyingly slow. Once the index is read from disk, it was quite fast, but the way sqlite works, there was no way I could find to prevent that particular behaviour.

Also, the fact that I have a giant postgres server (128GB of ram! 4TB of SSD storage!) for my other projects, and at this point know postgres quite well certainly contributed to the choice. When the options were "hand-roll a lot of manual caching stuff, which would be lots of effort" or "just use this set up postgres instance over there", the choice is pretty easy.

> also a note, that might be an windows issue. timezones fail to be recognized at all and needs to be edited manually. (atleast the error points to the right file to edit)

Timezones are basically programming sadness. It wouldn't surprise me if there are stupid tz issues somewhere.

**Comment by fake-name** [comment]
Ok, partial (broken) support for using sqlite as an alternative db backend is implemented in https://github.com/fake-name/xA-Scraper/tree/can_has_sqlite

It makes it to the point where it renders the web-ui, but a bunch of stuff is broken.

I think I might just rip out the existing migrations.

**Comment by CuddleBear92** [comment]
updated the wiki to have a silent startup on boot.

**Comment by fake-name** [comment]
I just [landed sqlite3 support](https://github.com/fake-name/xA-Scraper/commit/138b5c21e4b74e47bdbf7fce539ddb4d15df0887). 

This should make windows support (and general installing) a lot easier, assuming you're not trying to scrape thousands of artists.

**Comment by CuddleBear92** [comment]
thats amazing. dont think performance should be an issue at all. unless it tries to load everything at once. this should make it easier to use with all kinds of systems, not just windows aswell. will update the docs on it a bit later.

if performance is noticeable then caching data might be needed. either in a disk cache or ram cache. both should be faster than database loading in the long run.

**Comment by fake-name** [comment]
I think I mentioned it before, that the reason I moved to postgres for this in the first place was perf issues. 

Basically, when the scraper has been sitting for a while (hours), sqlite3 lets the indexes fall out of RAM. The next time they're needed, they have to be read from disk, and this can take a little while (30-45 seconds). This means the first time you view the web-ui typically takes a LONG time to finally display.
