### ISSUE TITLE
Problem with patreon captcha

### ISSUE THREAD

**Issue by reketeee** [fake-name/xA-Scraper#4]
Hi,

With lastest patreon site updates it's impossible to download anything.
It was working perfectly about 20 days ago but now (even with a correct cookie) fails.

Will you try to fix it? 

Many thanks :)

Btw, here is one of those error messages.
[error_patreon.txt](https://github.com/herp-a-derp/xA-Scraper/files/3562860/error_patreon.txt)

**Comment by herp-a-derp** [comment]
Yeah, this has been broken for a while. I've been ignoring it because I still had a login cookie and haven't had time to take a closer look.

ReCaptcha is fucking sadness.

**Comment by ImportTaste** [comment]
@fake-name Seems like the Patreon is broken again. So annoying.

**Comment by fake-name** [comment]
It seems to be working for me, though I've seen some issues with the login being kind of flaky. Can you try running it a few times?

I think the login probing has some issue I haven't been able to nail down yet.

**Comment by ImportTaste** [comment]
I actually ran it several times to no avail even before you asked. I very consistently get a 401 error. I'd give you a log but I don't think it's representative of the current commit since I had to revert some of the recent code.

**Comment by ImportTaste** [comment]
Oh. Apparently it was sending me a device verification emails.
```
 err_content=err_content, err_code=err_code, err_reason=err_reason)
WebRequest.Exceptions.FetchFailureError: <FetchFailureError 401 -> 'UNAUTHORIZED' for url: https://www.patreon.com/api/login?json-api-version=1.0 ({b'{"errors":[{"code":111,"code_name":"DeviceVerificationViaEmailRequired","detail":"Device Verification via Email Required","id":"thisiswhereanidwas","meta":{"checksum":"thisiswhereachecksumwas","context":"log in","redirect_target":null,"timestamp":1569698959,"verification_factor_email_id":thisiswhereanidwas},"status":"401","title":"device_verification_via_email_required"}]}'})>
```
There was just such a huge clusterfuck of errors that I missed this entirely.

**Comment by fake-name** [comment]
Yeah, that's patreon's standard auth flow:

 - Try to login. Fails.
 - Get email. Click link
 - Try to login again.
 - Works.

**Comment by fake-name** [comment]
Closing this because it was a unclear auth flow issue.
