### ISSUE TITLE
How good is this for scraping Patreon?

### ISSUE THREAD

**Issue by ylluminarious** [fake-name/xA-Scraper#419]
Hi,

I came across this project through your other project called [PatreonArchiver,](https://github.com/fake-name/PatreonArchiver) which you've apparently deleted now. Before the project was deleted, the README file indicated that this project is its effective successor and that the old project was not up-to-date with the Patreon API anymore. I would like to know whether this project is really better for archiving Patreon content. There is a person I donate to who uses Patreon effectively like a blog. He doesn't really upload artwork so much as links to Youtube videos and file attachments. He also makes textual posts. Is this project any good for archiving this kind of content from a Patreon creator?

Thanks.

**Comment by ylluminarious** [comment]
@fake-name Thanks for the detailed response. I'm sorry if my opening comment ruffled your feathers, I didn't mean any offense. I really was just wondering how well this tool works. It sounds like it will work sufficiently well for me.

> Currently, it saves what patreon calls the ['content', 'title' and 'tags' of posts](https://github.com/fake-name/xA-Scraper/blob/master/xascraper/modules/patreon/patreonScrape.py#L300-L303), as well as [posted files](https://github.com/fake-name/xA-Scraper/blob/master/xascraper/modules/patreon/patreonScrape.py#L313-L317) and [attachments](https://github.com/fake-name/xA-Scraper/blob/master/xascraper/modules/patreon/patreonScrape.py#L324-L327), though [embedded external content is currently only stubbed out](https://github.com/fake-name/xA-Scraper/blob/master/xascraper/modules/patreon/patreonScrape.py#L248-L256).

This sounds great. The external content is something that I can at least collect links for and scrape separately.

> Patreon's API is very noisy, and there is a lot of additional stuff in there that I don't think is worth preserving (tiers, costs, craploads of internal crosslinks, etc...), but that is basically an editorial decision on my part.

Yes, all that extra stuff is not important to me. I'm just interested in the actual content.

> Mostly, I don't have support for embeds right now because they're, well, hard to do in a sane manner. Realistically, for things like youtube, it'd probably be best to ship a list of links to something like youtube-dl or jdownloader, and since no-one I follow posts stuff on youtube I care about, I haven't bothered.

This sounds perfect. If I can collect a list of links of embedded Youtube videos and then ship them off to `youtube-dl`, as you said, then that will work just fine.

Thanks a lot for the info.

**Comment by ylluminarious** [comment]
@fake-name I'll go ahead and close this now and I'll open another issue if I run into trouble. Thanks again.

**Comment by fake-name** [comment]
> Thanks for the detailed response. I'm sorry if my opening comment ruffled your feathers, I didn't mean any offense. 

I wasn't bothered, mostly just a bit confused. No problem!

**Comment by ylluminarious** [comment]
@fake-name 

> I'll see about dumping the external links somewhere accessible.

Thanks! I would really appreciate that.

**Comment by fake-name** [comment]
Ok, the scraper now dumps out a giant file of the embed objects patreon gives me.

It's a little wordy, but it should be pretty easy to pull out whatever you want with a little regex action.

**Comment by ylluminarious** [comment]
@fake-name Awesome, thanks for implementing this and letting me know. From looking at the diff there, the file is called `post-embeds.pyson` right?

**Comment by fake-name** [comment]
Yep! 

`.pyson` is a semi-ad-hoc file format, it's basically a serialized python object (e.g. python serialized object notation). It looks a lot like json, but it's a little more flexible and less annoying about trailing commas, comments, etc....

**Comment by ylluminarious** [comment]
Hmm, very interesting. Thanks for the info!
