### ISSUE TITLE
Upon a new install, i get an SQL error

### ISSUE THREAD

**Issue by JarynCoresan** [fake-name/xA-Scraper#43]
See Screenshot - i get an SQLALCHEMY error on a clean reinstall of the scraper
![sql error](https://user-images.githubusercontent.com/32805275/33749738-4f149eaa-db84-11e7-8c83-78b2de001c59.png)

**Comment by JarynCoresan** [comment]
Bad screenshot - here is a better one
![sql error](https://user-images.githubusercontent.com/32805275/33749763-7437f402-db84-11e7-891f-ea05d8b3cce0.png)

**Comment by fake-name** [comment]
You need to update your settings file. There's been a few new members added to it, mostly to add support for sqlite as well..  

Have a look at the base file.

**Comment by fake-name** [comment]
Did that fix your issue?

**Comment by JarynCoresan** [comment]
it did fix that issue, but replaced it with another, see the screenshot;
![errorrevision](https://user-images.githubusercontent.com/32805275/34067047-a4a82228-e1cf-11e7-9c88-9e940d37131c.png)

**Comment by JarynCoresan** [comment]
Also, this was a clean setup.

**Comment by fake-name** [comment]
The revision `f058fce52fad` doesn't exist anymore, so you're not truly doing a clean install. 

Delete the `sqlite_db.db` from the project directory to fix the issue (or better, run `git clean -fxd`, though this will also delete everything not from the git checkout in the repository, do be careful).

Also, it's much, MUCH nicer to have actual pasted tracebacks, rather then screenshots.

**Comment by JarynCoresan** [comment]
I will keep that in mind - I though I had, since I deleted the entire project folder  and re-downloaded - but it didn't work. I solved it by tearing down the VM and rebuilding it from scratch. Its working now!

**Comment by fake-name** [comment]
> I though I had, since I deleted the entire project folder and re-downloaded - but it didn't work.

That's wierd. Were you using the sqlite backend, or the postgres backend? The sqlite backend, just deleting the folder would clear it out. With the postgres backend, you'd need to drop the database.

**Comment by JarynCoresan** [comment]
Aah, that would be it. I was using postgres. What would I have had to do exactly? Remove and recreate the database?

**Comment by fake-name** [comment]
Briefly (on the computer hosting the database);

```
# sudo -u postgres psql
> DROP DATABASE {your database name};
```

**Comment by JarynCoresan** [comment]
Got it - if this becomes an issue in the future I will try it out first. Thanks!
