### ISSUE TITLE
FA scraping apparently broken by layout change

### ISSUE THREAD

**Issue by mmsterful** [fake-name/xA-Scraper#6]
howdy, it's me again. I just got back to using this after being busy with other stuff, and it seems FurAffinity's fancy new layout broke the scraper. 

using scrape-manage.py complains that each gallery ends after one page and says that it can't find any items.

thank you again for your time and work on this tool! I haven't been able to get tumblr scraping working yet, but I haven't tried in a while and that needs more work on my end to ensure it's not my fault before I report it, lol.

log output:

```Main.Web - INFO - Request for URL: http://www.furaffinity.net/scraps/[artist]/1/ succeeded at Tue Jan 17 13:38:21 2017 On Attempt 1. Recieving...
Main.Web - INFO - URL fully retrieved.
Main.Web - INFO - Compression type = gzip. Content Size compressed = 6.562K. Decompressed = 20.292K. File type: text/html; charset=UTF-8.
Main.FaGet.Thread-3 - INFO - No more images. At end of gallery.
Main.FaGet.Thread-3 - INFO - Found 0 links
Main.FaGet.Thread-3 - WARNING - May be missing art? Total claimed art items from front-page = 95, total gallery items 0
Main.FaGet.Thread-3 - INFO - Previously retreived 80 items
Main.FaGet.Thread-3 - INFO - Old art items = 80, newItems = 0
Main.FaGet.Thread-3 - INFO - Successfully retreived content for artist [artist]
Main.FaGet.Thread-3 - INFO - GetArtist - 12342321

**Comment by fake-name** [comment]
This should be fixed, I think.

They fiddled with their layout a little bit. FA's whole site is hard to scrape in general, because it uses very old-style layout without many classes or other components to key off of, so the overall design winds up being a bit brittle.
