### ISSUE TITLE
Command for updating database filename extensions?

### ISSUE THREAD

**Issue by ImportTaste** [fake-name/xA-Scraper#62]
so, I'm not really versed in PostgreSQL, but maybe you can help me out. I want to repair the filenames for everything. I plan on first running TRiD recursively, then renaming all the JPEG variants to use .jpg, but after that I figure I'm going to need to make the database reflect the new filename.

I see that regular expressions are supported but only POSIX-style. Though there also seems to be a [third-party extension](https://github.com/petere/pgpcre) that can add pcre support (it would take time for me to figure out how to compile it for Windows and then enable it, however).

How would you approach this?

(As an aside, I really wish there was a regex type that supported right-to-left searches, it would make shit like this trivial, not to mention help people that use asian languages.)

**Comment by ImportTaste** [comment]
@fake-name I could still really use some help with this. I don't want to make a mistake and screw everything up.

**Comment by fake-name** [comment]
Somehow I didn't see this.

> TRiD 

That's not googlable. What is it?

> How would you approach this?

Write an [alembic migration](https://github.com/fake-name/xA-Scraper/tree/master/migrations/versions) for it that does both the renaming and the db fixes.

**Comment by ImportTaste** [comment]
@fake-name Here is [TRiD](http://mark0.net/soft-trid-e.html). It will use extensions like JFIF so if you use it in a shell script, make sure to catch those and rename them back to jpg.

As for the PostgreSQL commands, could I trouble you for examples? I have poked around in psql but I've never really executed commands to alter a database before, and I have been tripped up by some differences in syntax that PostgreSQL has compared to MySQL already.

Actually, I guess I should ask, within the database, is the extension stored separate from the filename, or is it part of the filename? If not... would it be possible for a database migration to be implemented in this project to start doing that? It seems like it would make this operation much easier, and may be useful in the future.

**Comment by fake-name** [comment]
> Here is TRiD. It will use extensions like JFIF so if you use it in a shell script, make sure to catch those and rename them back to jpg.

Ah, it's basically another libmagic type thing. 


> As for the PostgreSQL commands, could I trouble you for examples? I have poked around in psql but I've never really executed commands to alter a database before, and I have been tripped up by some differences in syntax that PostgreSQL has compared to MySQL already.

It's more confusing, because you don't really write SQL directly, much. You instead write python code that interacts with SQLAlchemy, so there's like 3 different contexts you have to be aware of. 

I do just write plain SQL sometimes just because I can't put together the correct alembic query.

> Actually, I guess I should ask, within the database, is the extension stored separate from the filename, or is it part of the filename? If not... would it be possible for a database migration to be implemented in this project to start doing that? It seems like it would make this operation much easier, and may be useful in the future.

It's [one function](https://docs.python.org/3.7/library/os.path.html#os.path.splitext) to go from one to the other, so  I don't see a reason. to bother. 

Really, I barely do anything directly in the DB.
