### ISSUE TITLE
TwitGet retrieving lower-res versions of artwork

### ISSUE THREAD

**Issue by ImportTaste** [fake-name/xA-Scraper#71]
@fake-name `:orig` is not being asserted at the end of the image URL, so you are getting a much lower resolution than what is available. Here is what TwitGet downloaded:

[Click here (NSFW)](https://user-images.githubusercontent.com/53661808/69035752-f901f700-09a9-11ea-8eb5-8789c7393554.jpg) From: https://twitter.com/sundayshu/status/1176074836252037120

And here is the full resolution available on Twitter:

https://pbs.twimg.com/media/EFJB0nkU8AAGXjC.jpg:orig

~200kb vs almost 1MB.

**Comment by fake-name** [comment]
That's what I get for not even looking at the HTML **at all**.
