### ISSUE TITLE
File naming conventions for DA

### ISSUE THREAD

**Issue by jimhsu** [fake-name/xA-Scraper#75]
Hi,

Is there the possibility of changing file naming conventions for deviantart? This is important for secondary organization of photos, as the current convention (inserting full URL without delimiters before filename) wrecks most forms of secondary photo organization as well as natural search engines (which expect at least a delimiter). This doesn't seem to be a problem with the other scraper locations. I can't deal with hundreds of thousands of files that look like this anymore:

![image](https://user-images.githubusercontent.com/56103/36505320-ba8b8214-1718-11e8-85ec-6b9cb9cd5aa6.png)

I realize this may break currently synced photos in the web interface, but I'd rather deal with a full resync than try to write some form of cron script to periodically fix this.

**Comment by fake-name** [comment]
Yeah, I've been meaning to figure out wtf happened here. It is really annoying.

**Comment by jimhsu** [comment]
Used the following in a script for a quick workaround. Not perfect, but it mostly works.

find -iname \* | rename 's/httpswww.deviantart.comdownload[0-9]*//gi'
find -iname \* | rename 's/httpsimg00.deviantart.net[0-9a-z]{14}//gi'
find -iname \* | rename 's/httpsorig00.deviantart.net[0-9a-z]{14}//gi'

**Comment by fake-name** [comment]
Avoid changing things manually. I should have a migration in a day or two that fixes things automatically.

**Comment by fake-name** [comment]
Ok, that migration should both fix the poorly named files, and also update the database to track the new files.

**Comment by fake-name** [comment]
As a bonus, the fixer comes with fancy progress output:

![progress](https://user-images.githubusercontent.com/1401239/36580860-ebb66e60-181e-11e8-9ee1-4cc8532ed42d.gif)

**Comment by jimhsu** [comment]
Works. Thank you! 💯

**Comment by fake-name** [comment]
Woot!
