### ISSUE TITLE
Tumblr scraper seems to not handle API rate limit gracefully

### ISSUE THREAD

**Issue by mmsterful** [fake-name/xA-Scraper#8]
There's a very large blog among others I'm trying to mirror, and I think I ran into Tumblr's API rate limit of 1000 requests per hour/5000 per day. It fetched the various blogs in the lost before it, then fetched the large blog's posts up to offset 11440, before moving on to the next blogs and apparently fetching no posts. After that, it threw an exception:

```python
Main - CRITICAL - Uncaught exception!
Main - CRITICAL - Uncaught exception
Traceback (most recent call last):
  File "./scrape-manage.py", line 198, in <module>
    go()
  File "./scrape-manage.py", line 174, in go
    do_fetch(sys.argv[1:])
  File "./scrape-manage.py", line 94, in do_fetch
    do_plugin(plg)
  File "./scrape-manage.py", line 70, in do_plugin
    instance.go(ctrlNamespace=namespace)
  File "/mnt/h/xA-Scraper/plugins/scrapers/ScraperBase.py", line 327, in go
    errored  |= future.result()
  File "/usr/lib/python3.4/concurrent/futures/_base.py", line 395, in result
    return self.__get_result()
  File "/usr/lib/python3.4/concurrent/futures/_base.py", line 354, in __get_result
    raise self._exception
  File "/usr/lib/python3.4/concurrent/futures/thread.py", line 54, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/mnt/h/xA-Scraper/plugins/scrapers/tumblr/tumblrScrape.py", line 230, in getArtist
    artPages = self._getGalleries(artist)
  File "/mnt/h/xA-Scraper/plugins/scrapers/tumblr/tumblrScrape.py", line 204, in _getGalleries
    addposts = self.t.get('posts', blog_url=baseUrl, params={"limit" : step, 'offset':offset})
  File "/mnt/h/xA-Scraper/venv/lib/python3.4/site-packages/tumblpy/api.py", line 179, in get
    extra_endpoints=extra_endpoints, params=params)
  File "/mnt/h/xA-Scraper/venv/lib/python3.4/site-packages/tumblpy/api.py", line 173, in request
    raise TumblpyError(error_message, error_code=response.status_code)
tumblpy.exceptions.TumblpyError: There was an error making your request.
Main.TumblrGet - INFO - Unoading TumblrGet
Main.TumblrGet - INFO - Closing DB...
Exception ignored in: <bound method GetTumblr.__del__ of <plugins.scrapers.tumblr.tumblrScrape.GetTumblr object at 0x7fa1088ad048>>
Traceback (most recent call last):
  File "/mnt/h/xA-Scraper/plugins/PluginBase.py", line 46, in __del__
  File "/mnt/h/xA-Scraper/plugins/PluginBase.py", line 74, in closeDB
  File "/mnt/h/xA-Scraper/plugins/PluginBase.py", line 102, in __getattribute__
  File "/mnt/h/xA-Scraper/venv/lib/python3.4/site-packages/psycopg2/__init__.py", line 162, in connect
  File "/mnt/h/xA-Scraper/venv/lib/python3.4/site-packages/psycopg2/__init__.py", line 162, in <listcomp>
  File "/mnt/h/xA-Scraper/venv/lib/python3.4/site-packages/psycopg2/__init__.py", line 93, in _param_escape
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2222, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 2155, in _find_spec
TypeError: 'NoneType' object is not iterable
Main.Web - INFO - Trying to save cookies!
Main.Web - INFO - Synchronizing cookies with cookieFile.
Encountered an error on exit?
Exception = name 'open' is not defined
Main.StatusMgr - INFO - Closing DB...
Main.StatusMgr - INFO - done
```

I've requested a rate limit removal, but I have no idea how that'll go. Some sort of error handling and maybe pause for an hour or a day, or suspend/resume functionality, for the scraper would be bitchin'.

My version is a few commits behind as I'm not quite sure how to properly use Git to update the local version while keeping my settings.

**Comment by mastic544** [comment]
Finally someone alive on this project!
Could you spare a moment and help me setup this thing? I'm pretty fresh to github and python...
I wanted to write to the dev but i simply couldn't find any options to send PMs on github.

**Comment by fake-name** [comment]
This is embarrassing, but I didn't realize tumblr *had* API limits. Derp.

I'll see about making it handle the rate-limiting more gracefully.

**Comment by mastic544** [comment]
@fake-name Many thanks for the walktrough, and many more for sharing such an awesome creation.

**Comment by fake-name** [comment]
@mastic544  - Yeah, I mean run `./run.sh`. Assuming you're in bash, it should work.

It'd probably just fail spectacularly on windows. I'm not sure what `cmd.exe` would even do with bash syntax.

**Comment by mastic544** [comment]
@fake-name ...well rip. I'm on windows. I thought cmd could run .sh... riiight, .bat. Darn. Would virtualBox and linux mint work if i just move the whole thing there?

**Comment by fake-name** [comment]
That would work. Alternatively, I *think* everything would probably work on windows, I've just ever even tested it. You'd have to setup the virtualenv manually, and install the needed packages yourself (or you could even not bother with the venv). 

YMMV.

**Comment by mastic544** [comment]
hm. well, i guess i'll just try everything and see what works.

**Comment by mmsterful** [comment]
If you're part of the Windows Insider Program, the Linux on Windows subsystem makes it remarkably easy. I'm running Postgres under Windows, and the rest of it under Linux-on-Windows.

**Comment by fake-name** [comment]
Heh, HELPING.

------

I was thinking about the rate limiting. Right now, the scraper doesn't touch the same content twice. I'd think it would incrementally fetch more and more of the content for the artists you're scraping. As such, I assume it'd eventually get all the content you want to scrape.

The only case I can see this not working is if you have so many sources you want to archive that you wound up with more then 5000 resource list requests (this'd probably require several hundred sources at minimum).

The only way I can think of to work around this is by either supporting multiple accounts, or having a mechanism to incrementally walk your scrape list over several days. 

Personally, I'm inclined to the latter more then the former (less work), and it'd still get all the content over time.

**Comment by mmsterful** [comment]
That would be the issue; some of the aggregator blogs I follow have so many posts that it's impossible for it to fetch them all without hitting the limit. Incrementally doing it seems like the way to go.

I wonder if there's some way to do delta scrapes (maybe not just for Tumblr), where the scraper figures out when it hits where it stopped last time, and stops making resource requests.

**Comment by fake-name** [comment]
I already do delta scrapes to some extent, basically I only fetch new /posts/.

The issue is I walk the whole post history every time, which with high-volume sources is apparently enough to hit the limits.

Realistically, I could just fetch content until I hit something I'd seen, and that'd probably let the system keep up with new stuff without too much trouble (barring how the reblogging shit works). Right now, I don't have any system for maintaining that kind of state, principally because the original target of the scraper was sites where the content was not chronologically ordered (e.g. art galleries).

It shouldn't be too hard to implement, I just haven't had time recently.

**Comment by fake-name** [comment]
Ok, this should be partially done (it remembers which artist it scrapes, but it doesn't not walk the entire history for each artist).
