### ISSUE TITLE
Please throw me a bone, I'm at my wit's end

### ISSUE THREAD

**Issue by Aidolii** [fake-name/xA-Scraper#82]
I hate asking for help, but after spending roughly 12 hours trying to get the YP functionality to work on my Windows machine, my brain is fried. I have no idea how to get the autotriever working properly. 

I even went and got msys2, which was a headache and a half, only to learn that apparently, chromedriver will say it's an unsupported platform. (even though I thought the whole point of python was to be cross-platform...)

Please help me. I can't even tell you where I'm stuck at. I feel like I'm no closer to figuring out how to get it to work than when I began.

**Comment by fake-name** [comment]
The YP scraper is..... **extremely** involved. See the note: `(Requires additional RPC infrastructure)`.

Basically, you're gonna need a public-facing [RabbitMQ](https://www.rabbitmq.com/) instance with a world-resolvable domain name, and an account on Google compute engine, Digital Ocean, Linode, or Vultr. 

Then, you use the [Autotriever Marshaller system](https://github.com/fake-name/AutoTriever/tree/master/marshaller) to automatically deploy RPC workers on one (or more) of the above cloud services, which call home to the RabbitMQ server, which acts as the broker for the [FetchAgent component of *another* of my projects](https://github.com/fake-name/ReadableWebProxy/tree/master/FetchAgent), which handles local arbitrating of access and transfer-unchunking of the job responses dispatched over AMQP.

Realistically, the YP scraper is basically not useable unless you have pretty much *every single* one of my silly hobby projects installed and active.

**Comment by Baddest-Juju** [comment]
yikes...

I don't suppose you have any plans to improve it?

**Comment by Baddest-Juju** [comment]
If I knew how to program it I wouldn't be here :V

**Comment by Aidolii** [comment]
Does anyone involved with the project currently have any plans to make the feature more... accessible?

This is far beyond my ability to poke at.

**Comment by fake-name** [comment]
AFICT, I'm literally the only person who's involved, and not at the moment. 

Sorry!
