### ISSUE TITLE
Running scrape-manage.py on newest revision results in error

### ISSUE THREAD

**Issue by mmsterful** [fake-name/xA-Scraper#9]
I updated to the newest version with the consolidated management interface, and had an issue using it.

After activating the virtualenv (source venv/bin/activate):

```
(venv) username@hostname:/mnt/h/xA-Scraper/manage$ python3 scrape_manage.py
Traceback (most recent call last):
  File "scrape_manage.py", line 2, in <module>
    from plugins.scrapers.da.daScrape import GetDA
ImportError: No module named 'plugins'
(venv) username@hostname:/mnt/h/xA-Scraper/manage$
```

The same issue occurs running it from the base directory too, and after activating the venv from the manage/ dir to see if it would make any difference.

I'm unsure if this is a problem with the code, or if there's a new way to do things I don't know about. :)

**Comment by mmsterful** [comment]
After looking up what __main__.py does, I tried running the directory:
```
(venv) username@hostname:/mnt/h/xA-Scraper/manage$ python3 scrape_manage.py
Traceback (most recent call last):
  File "scrape_manage.py", line 2, in <module>
    from plugins.scrapers.da.daScrape import GetDA
ImportError: No module named 'plugins'
```

**Comment by fake-name** [comment]
it's moved about, sorry.

The correct invocation is `python3 -m manage`.

**Comment by mmsterful** [comment]
Ahh, I tried `python3 -m manage/` wiyj no results That works. Thanks!

**Comment by fake-name** [comment]
Yeah, you can't have a slash in a python module name.
