### ISSUE TITLE
fAGet broke as fuck

### ISSUE THREAD

**Issue by ImportTaste** [fake-name/xA-Scraper#93]
http://www.furaffinity.net/journal/9406201

Tried to fix it myself but they seem to have torn out every convenient identifier of sections from the class names.

**Comment by ImportTaste** [comment]
@fake-name 
https://github.com/mikf/gallery-dl/blob/master/gallery_dl/extractor/furaffinity.py

**Comment by fake-name** [comment]
Are these further changes from the rework recently?

**Comment by ImportTaste** [comment]
Yes, lots of changes unfortunately.

**Comment by fake-name** [comment]
Seems to work now. Only thing actually broken was the total art count extraction. 

It's fixed, but super brittle now. Argh.
